import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my bookshop!</h1>
        <div
          className="flex flex-col w-60 mt-2 py-2
         h-30 border-2 border-slate-400 text-center"
        >
          <label>Books</label>
          <input
            type="text"
            className="border-slate-400 border-2 mx-auto my-2 w-3/4 h-full"
          />
          <label>Collections</label>
          <input
            type="text"
            className="border-slate-400 border-2 mx-auto my-2 w-3/4 h-full"
          />
          <button
            type="submit"
            className="mx-auto my-2 w-3/4 h-full bg-blue-400 b-2 border-black"
          >
            Click me!
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
